Repository Nawabali-project/Nawabali-BE, pull requests merged in 2024-05, with the labels that each got.

#163 FIX : 채팅, 알림 리팩토링
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
  src/main/java/com/nawabali/nawabali/constant/MessageType.java
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/controller/NotificationController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/domain/Notification.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/dto/ChattingRequest.java
  src/main/java/com/nawabali/nawabali/dto/NotiDeleteResponseDto.java
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketChatRoomCount.java
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
  src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/security/Jwt/WebSocketJwtInterceptor.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#164 FIX : post 관련 코드 정리
  src/main/java/com/nawabali/nawabali/constant/Town.java
  src/main/java/com/nawabali/nawabali/domain/Post.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/exception/GlobalExceptionAdvice.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#165 FIX : 페이저블 빼기, 검색시 다른 검색어도 같이 검색되는 것 수정 / null exception 추가 / 검색결과가 없을때 값을 보내지 않기
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: fix

#169 FIX : 페이저블 추가
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: fix

#172 bug : 채팅 저장이 안되는 에러
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: bug

#173 FIX : 채팅 메세지 보낼때 저장 안되는 오류
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#175 fix : 리팩토링 & 채팅방 상대방 대화 조회
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/controller/LikeController.java
  src/main/java/com/nawabali/nawabali/domain/Comment.java
  src/main/java/com/nawabali/nawabali/domain/Like.java
  src/main/java/com/nawabali/nawabali/dto/CommentDto.java
  src/main/java/com/nawabali/nawabali/dto/LikeDto.java
  src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
  src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#176 FIX : 채팅 쿼리 dsl 리팩토링
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#178 FIX : 채팅메세지 메인에 오는것
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: fix

#182 FIX : subscribe할때 unreadMessageCount 보내기
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#179 게시글 일괄 조회 및 일괄수정 API 추가
  .idea/dataSources.xml
  build.gradle
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/domain/Post.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/PostSearch.java
  src/main/java/com/nawabali/nawabali/exception/GlobalExceptionAdvice.java
  src/main/java/com/nawabali/nawabali/global/tool/redis/RedisConfig.java
  src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#191 release 서버에 있던 코드를 develop으로 pr
  .gitattributes
  .github/workflows/cicd_production.yml
  .gitignore
  .idea/dataSources.xml
  appspec.yml
  build.gradle
  scripts/health.sh
  scripts/profile.sh
  scripts/start.sh
  scripts/stop.sh
  scripts/switch.sh
  src/main/java/com/nawabali/nawabali/HelloController.java
  src/main/java/com/nawabali/nawabali/NawabaliApplication.java
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/controller/UserController.java
  src/main/java/com/nawabali/nawabali/domain/image/PostImage.java
  src/main/java/com/nawabali/nawabali/dto/CommentDto.java
  src/main/java/com/nawabali/nawabali/dto/OAuthDto.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/UserSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthorizationFilter.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtLogoutHandler.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/KakaoService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
  src/test/java/com/nawabali/nawabali/postTest/PostDslTest.java
  src/test/java/com/nawabali/nawabali/service/PostSearchTest.java
  src/test/java/com/nawabali/nawabali/service/PostServiceTest.java
Labels: fix

#192 테스트 위한 log
  src/main/generated/com/nawabali/nawabali/domain/QPost.java
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#194 FIX : 테스트위한 log
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#195 FIX : 테스트위한 log 추가
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#196 FIX : 테스트위한 log 알림 추가
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#197 FIX : 테스트위한 log 알림 추가
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#198 FIX : 테스트위한 log 알림 추가
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#199 FIX : 테스트위한 log 알림 추가
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
Labels: fix

#201 FIX : 테스트위한 log 알림 추가
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
Labels: fix

#202 FIX : 테스트위한 log 알림 추가 , null 추가
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
Labels: fix

#203 FIX : 테스트위한 변수명 교체 : 웹소켓
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
Labels: fix
