Repository Nawabali-project/Nawabali-BE, pull requests merged in 2024-04, with the labels that each got.

#24 Feat : 게시물 전체 조회 시 무한 스크롤 구현
  nawabali/build.gradle
  nawabali/src/main/generated/com/nawabali/nawabali/constant/QAddress.java
  nawabali/src/main/generated/com/nawabali/nawabali/constant/QTown.java
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QPost.java
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QTimeStamp.java
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QUser.java
  nawabali/src/main/generated/com/nawabali/nawabali/domain/image/QPostImage.java
  nawabali/src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/PostController.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/PostDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/SignupDto.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/PostImageRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/PostRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustom.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustomImpl.java
  nawabali/src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#29 프로필사진 생성, 수정, 삭제 구현
  nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/image/ProfileImage.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/UserDto.java
  nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/ProfileImageRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement

#30 회원정보 CRUD 수정
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QUser.java
  nawabali/src/main/generated/com/nawabali/nawabali/domain/image/QProfileImage.java
  nawabali/src/main/java/com/nawabali/nawabali/constant/UserRankEnum.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/SignupDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/UserDto.java
  nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement

#31 댓글 작성 / 수정 / 삭제
  .gitignore
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  nawabali/src/main/java/com/nawabali/nawabali/constant/LikeCategory.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/CommentController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/LikeController.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/Comment.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/Like.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/LocalLike.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/CommentDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/LikeDto.java
  nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/LocalLikeRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/service/CommentService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/LikeService.java
Labels: enhancement

#32 Swagger 적용
  nawabali/.gitignore
  nawabali/build.gradle
  nawabali/src/main/java/com/nawabali/nawabali/config/SwaggerConfig.java
  nawabali/src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/SignupDto.java
  nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  nawabali/src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthorizationFilter.java
  nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement

#36 Feat : 북마크 토글 형태 / 유저 북마크 조회 기능 구현
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QBookMark.java
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QPost.java
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QUser.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/PostController.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/BookMark.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/Comment.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/Post.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/BookMarkDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/CommentDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/PostDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/UserDto.java
  nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/BookMarkRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/service/BookMarkService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/LikeService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/PostService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement

#37 Feat : 카카오 로그인
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QUser.java
  nawabali/src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  nawabali/src/main/java/com/nawabali/nawabali/constant/Address.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/KakaoController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/KakaoDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/UserDto.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/UserRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
  nawabali/src/main/java/com/nawabali/nawabali/service/KakaoService.java
  nawabali/src/main/resources/static/css/style.css
  nawabali/src/main/resources/static/js/basic.js
  nawabali/src/main/resources/templates/login.html
Labels: enhancement

#40 좋아요 리팩토링
  nawabali/src/main/java/com/nawabali/nawabali/constant/LikeCategory.java
  nawabali/src/main/java/com/nawabali/nawabali/constant/LikeCategoryEnum.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/LikeController.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/Like.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/LikeDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/PostDto.java
  nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/service/LikeService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#41 Feat : 댓글 조회 무한 스크롤 & 게시물 조회 부분 수정
  nawabali/src/main/generated/com/nawabali/nawabali/domain/QPost.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/CommentController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/PostController.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/Like.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/Post.java
  nawabali/src/main/java/com/nawabali/nawabali/domain/User.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/PostDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/dslDto/CommentDslDto.java
  nawabali/src/main/java/com/nawabali/nawabali/dto/dslDto/PostDslDto.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/ProfileImageRepository.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/dslrepository/CommentDslRepositoryCustom.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/dslrepository/CommentDslRepositoryCustomImpl.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustom.java
  nawabali/src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustomImpl.java
  nawabali/src/main/java/com/nawabali/nawabali/service/CommentService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/KakaoService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#44 fix : 코드 리펙토링 및 스웨거 설명
  nawabali/src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/CommentController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/EmailController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/LikeController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/PostController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/UserController.java
  nawabali/src/main/java/com/nawabali/nawabali/controller/UserImageController.java
  nawabali/src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  nawabali/src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  nawabali/src/main/java/com/nawabali/nawabali/service/ImageService.java
  nawabali/src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: fix

#49 게시물 내용 검색 기능
  .idea/dataSources.xml
  .idea/gradle.xml
  build.gradle
  src/main/generated/com/nawabali/nawabali/constant/QAddress.java
  src/main/generated/com/nawabali/nawabali/constant/QTown.java
  src/main/generated/com/nawabali/nawabali/domain/QBookMark.java
  src/main/generated/com/nawabali/nawabali/domain/QComment.java
  src/main/generated/com/nawabali/nawabali/domain/QLike.java
  src/main/generated/com/nawabali/nawabali/domain/QPost.java
  src/main/generated/com/nawabali/nawabali/domain/QTimeStamp.java
  src/main/generated/com/nawabali/nawabali/domain/QUser.java
  src/main/generated/com/nawabali/nawabali/domain/image/QPostImage.java
  src/main/generated/com/nawabali/nawabali/domain/image/QProfileImage.java
  src/main/java/com/nawabali/nawabali/controller/PostSearchController.java
  src/main/java/com/nawabali/nawabali/domain/Post.java
  src/main/java/com/nawabali/nawabali/domain/elastic/PostSearch.java
  src/main/java/com/nawabali/nawabali/repository/elasticRepository/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/service/PostSearchService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#50 로그아웃추가, 카카오컨트롤러 수정.
  .idea/dataSources.xml
  src/main/generated/com/nawabali/nawabali/constant/QAddress.java
  src/main/generated/com/nawabali/nawabali/constant/QTown.java
  src/main/generated/com/nawabali/nawabali/domain/QBookMark.java
  src/main/generated/com/nawabali/nawabali/domain/QComment.java
  src/main/generated/com/nawabali/nawabali/domain/QLike.java
  src/main/generated/com/nawabali/nawabali/domain/QPost.java
  src/main/generated/com/nawabali/nawabali/domain/QTimeStamp.java
  src/main/generated/com/nawabali/nawabali/domain/QUser.java
  src/main/generated/com/nawabali/nawabali/domain/image/QPostImage.java
  src/main/generated/com/nawabali/nawabali/domain/image/QProfileImage.java
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/controller/KakaoController.java
  src/main/java/com/nawabali/nawabali/controller/UserController.java
  src/main/java/com/nawabali/nawabali/domain/User.java
  src/main/java/com/nawabali/nawabali/dto/SignupDto.java
  src/main/java/com/nawabali/nawabali/global/tool/redis/RedisConfig.java
  src/main/java/com/nawabali/nawabali/repository/UserRepository.java
  src/main/java/com/nawabali/nawabali/repository/dslrepository/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthenticationFilter.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthorizationFilter.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtLogoutHandler.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
  src/main/java/com/nawabali/nawabali/service/KakaoService.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
  src/main/resources/templates/index.html
Labels: enhancement, fix

#52 웹소켓 + stomp 채팅 기능
  .gitignore
  build.gradle
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
  src/main/resources/templates/chat/room.html
  src/main/resources/templates/chat/roomdetail.html
Labels: enhancement

#56 FEAT : FE 요구사항에 따른 수정
  src/main/generated/com/nawabali/nawabali/domain/QPost.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/controller/EmailController.java
  src/main/java/com/nawabali/nawabali/domain/Post.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/dto/dslDto/CommentDslDto.java
  src/main/java/com/nawabali/nawabali/dto/dslDto/PostDslDto.java
  src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/BookMarkService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/test/java/com/nawabali/nawabali/repository/PostDslRepositoryCustomImplTest.java
Labels: enhancement, fix

#57 게시물 상세조회시 반환내역 중 작성자 프로필 이미지 추가
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/repository/ProfileImageRepository.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#62 FEAT : 카테고리/구 별 게시물 조회
  .idea/dataSources.xml
  src/main/generated/com/nawabali/nawabali/constant/QTown.java
  src/main/java/com/nawabali/nawabali/constant/Town.java
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/controller/elasticsearch/PostSearchController.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/PostSearch.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/PostDslDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
  src/main/java/com/nawabali/nawabali/repository/PostRepository.java
  src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/dslrepository/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/main/java/com/nawabali/nawabali/service/elasticsearch/PostSearchService.java
  src/test/java/com/nawabali/nawabali/repository/PostDslRepositoryCustomImplTest.java
Labels: enhancement

#60 알림 기능 : 메세지 / 좋아요 / 로컬 좋아요 / 댓글
  .gitignore
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/controller/NotificationController.java
  src/main/java/com/nawabali/nawabali/domain/Notification.java
  src/main/java/com/nawabali/nawabali/dto/NotiDeleteResponseDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
  src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
  src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: documentation

#63 Fix : Post 사진 업로드 수정
  src/main/java/com/nawabali/nawabali/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
Labels: enhancement, fix

#64 chat / notification 리팩토링
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
  src/main/java/com/nawabali/nawabali/constant/MessageType.java
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/controller/NotificationController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/domain/Notification.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/dto/NotiDeleteResponseDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
  src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#66 좋아요, 로컬좋아요 합계 계산 추가 및 기타 코드 수정,삭제
  .idea/compiler.xml
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
  src/main/java/com/nawabali/nawabali/controller/KakaoController.java
  src/main/java/com/nawabali/nawabali/controller/UserController.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/dto/UserDto.java
  src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  src/main/java/com/nawabali/nawabali/repository/PostRepository.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthenticationFilter.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtLogoutHandler.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
  src/main/java/com/nawabali/nawabali/service/KakaoService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement, fix

#68 회원가입시 기본 프로필사진 지정
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/constant/DefaultProfileImage.java
  src/main/java/com/nawabali/nawabali/controller/UserImageController.java
  src/main/java/com/nawabali/nawabali/domain/image/ProfileImage.java
  src/main/java/com/nawabali/nawabali/dto/UserDto.java
  src/main/java/com/nawabali/nawabali/service/ImageService.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement

#71 REFACTOR : ElasticSearch 기능 수정 , config 파일 추가
  build.gradle
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/config/QueryDslConfig.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/PostSearch.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/PostDslDto.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/main/resources/elastic/es-mapping.json
  src/main/resources/elastic/es-setting.json
Labels: fix

#74 FIX : Elastic 보안 삭제
  .idea/dataSources.xml
  build.gradle
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/controller/elasticsearch/PostSearchController.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/PostSearch.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthenticationFilter.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/main/java/com/nawabali/nawabali/service/elasticsearch/PostSearchService.java
  src/main/resources/elastic/es-mapping.json
  src/main/resources/elastic/es-setting.json
  src/test/java/com/nawabali/nawabali/postTest/PostDslTest.java
Labels: bug, fix

#73 동네별 점수 조회
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  src/main/java/com/nawabali/nawabali/repository/PostRepository.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#76 FIX : 유저 북마크 조회 시 무한 스크롤로 구현
  .idea/dataSources.xml
  src/main/generated/com/nawabali/nawabali/domain/QBookMark.java
  src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/domain/BookMark.java
  src/main/java/com/nawabali/nawabali/dto/BookMarkDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/BookmarkDslDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/BookMarkService.java
  src/test/java/com/nawabali/nawabali/commentTest/CommentDslTest.java
Labels: enhancement, fix

#77 동네별 점수 조회 _ 전체 구 리스트로 반환
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement, fix

#80 전체 조회시 프로필이미지 반환
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#78 대댓글 페이지네이션 구현
  .idea/dataSources.xml
  src/main/generated/com/nawabali/nawabali/domain/QComment.java
  src/main/generated/com/nawabali/nawabali/domain/QTimeStamp.java
  src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/controller/EmailController.java
  src/main/java/com/nawabali/nawabali/controller/KakaoController.java
  src/main/java/com/nawabali/nawabali/controller/LikeController.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/controller/UserController.java
  src/main/java/com/nawabali/nawabali/domain/BookMark.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/domain/Comment.java
  src/main/java/com/nawabali/nawabali/domain/Like.java
  src/main/java/com/nawabali/nawabali/domain/Post.java
  src/main/java/com/nawabali/nawabali/domain/TimeStamp.java
  src/main/java/com/nawabali/nawabali/domain/User.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/PostSearch.java
  src/main/java/com/nawabali/nawabali/domain/image/ProfileImage.java
  src/main/java/com/nawabali/nawabali/dto/CommentDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/CommentRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
Labels: enhancement, fix

#81 내가 쓴 게시글 조회
  src/main/java/com/nawabali/nawabali/controller/UserController.java
  src/main/java/com/nawabali/nawabali/repository/LikeRepository.java
  src/main/java/com/nawabali/nawabali/repository/PostRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthenticationFilter.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement

#83 FIX : 코드 리펙토링
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/domain/BookMark.java
  src/main/java/com/nawabali/nawabali/domain/Post.java
  src/main/java/com/nawabali/nawabali/domain/image/PostImage.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/service/BookMarkService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement, fix

#84 FEAT : 게시물 상세 조회시 반환 값에 토글링 여부 추가.
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement, fix

#85 F IX : QueryDSL 메서드 분리 작업
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement, fix

#89 1:1 / 1:N 채팅방 생성 구분 및 본인의 채팅방 조회시 1:1 채팅방의 이름은 상대방의 nickname으로 설정
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
  src/main/java/com/nawabali/nawabali/constant/ChatRoomEnum.java
  src/main/java/com/nawabali/nawabali/constant/MessageType.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
  src/main/java/com/nawabali/nawabali/repository/UserRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#87 FEAT : 최근 일주일간 작성된 게시글을 좋아요가 많은 순으로 상위 10개조회
  src/main/java/com/nawabali/nawabali/constant/LikeCategoryEnum.java
  src/main/java/com/nawabali/nawabali/constant/Period.java
  src/main/java/com/nawabali/nawabali/controller/LikeController.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/security/UserDetailsServiceImpl.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#90 FEAT : 댓글 반환값에 작성자 프로필이미지, 주거지, 회원등급 추가 반환
  src/main/java/com/nawabali/nawabali/dto/UserDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
Labels: enhancement

#92 FIX : 댓글 조회 반환값 순서 변경
  src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
Labels: fix

#93 FIX : 채팅방 내용 조회시 thymeleaf 에러 해결
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: enhancement, fix

#95 지역별 제일 많은 게시물 카테고리 & 캐스팅 오류 해결
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/repository/PostRepository.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement, fix

#96 FIX : 채팅에 log.debug 구현
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: enhancement

#98 FEAT : 메세지 전송시 response 보내기 & 서버 로그 종료 방지 코드 추가
  build.gradle
  src/main/java/com/nawabali/nawabali/NawabaliApplication.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: bug, enhancement

#99 FIX : 메세지 전송시 response 보내기 수정
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#100 FEAT : 각 카테고리 별 최근 한달(일주)간 게시글이 제일 많았던 구 및 게시글 수 출력
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/controller/BookMarkController.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/dto/BookMarkDto.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/BookmarkDslDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/PostDslDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/BookMarkService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/test/java/com/nawabali/nawabali/postTest/PostDslTest.java
Labels: enhancement, fix

#101 FEAT : 메세지 DTO 수정 & 채팅방 프로필 사진
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: fix

#103 FEAT : 구 와 기간별 각 카테고리의 게시글 개수
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/test/java/com/nawabali/nawabali/postTest/PostDslTest.java
Labels: enhancement

#107 FIX : 메세지 dto 보내기
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#106 FIX : 동네별 점수 조회 메서드 리펙토링(메소드 분리)
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/constant/Address.java
  src/main/java/com/nawabali/nawabali/domain/User.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: fix

#108 feat : 무중단배포 적용
  .github/workflows/cicd_production.yml
  appspec.yml
  build.gradle
  scripts/health.sh
  scripts/profile.sh
  scripts/start.sh
  scripts/stop.sh
  scripts/switch.sh
  src/main/java/com/nawabali/nawabali/HelloController.java
  src/main/java/com/nawabali/nawabali/ProfileController.java
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
Labels: enhancement

#109 FIX : 메세지 dto 반환
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: fix

#112 FIX : 메세지 dto 보내기 수정
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#113 FIX : 메세지 전송 수정
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/dto/ChattingRequest.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: fix

#114 FIX : 메세지 전송 dto수정
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#115 FIX : 게시물 API 요청값 및 반환값 수정
  .idea/dataSources.xml
  src/main/generated/com/nawabali/nawabali/constant/QTown.java
  src/main/java/com/nawabali/nawabali/constant/Town.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/test/java/com/nawabali/nawabali/service/PostServiceTest.java
Labels: enhancement, fix

#118 게시글 최적화를 위한 반환 값 수정
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: fix

#119 FEAT : 채팅 인증인가 & 실시간
  src/main/java/com/nawabali/nawabali/config/WebSocketConfig.java
  src/main/java/com/nawabali/nawabali/controller/ChatController.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketChatRoomCount.java
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/ChatRoomRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
  src/main/java/com/nawabali/nawabali/security/Jwt/WebSocketJwtInterceptor.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: enhancement

#122 feat : default 프로필 이미지 수정
  .idea/compiler.xml
  src/main/java/com/nawabali/nawabali/constant/DefaultProfileImage.java
Labels: enhancement

#124 FEAT : 유저 닉네임으로 게시물 조회
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#125 회원 정보 조회 API 추가 및 닉네임 검색시 반환값추가
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/controller/UserController.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/UserSearch.java
  src/main/java/com/nawabali/nawabali/dto/UserDto.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement, fix

#127 FIX : getUserPost 메소드 수정
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#126 FIX : notification id 추가
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#128 FIX : 본인 전체 채팅방 조회_최근메세지 + 프로필 사진 & 전체 메세지 조회_상대방 프로필 사진 보내기 + dto 정리
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: fix

#130 FIX : 북마크 조회시 반환값 수정
  src/main/java/com/nawabali/nawabali/constant/UserRankEnum.java
  src/main/java/com/nawabali/nawabali/domain/User.java
  src/main/java/com/nawabali/nawabali/dto/BookMarkDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/bookmark/BookmarkDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/BookMarkService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: fix

#131 FEAT : post 작성시, 등급 업그레이드 기준에 맞으면 등급업 시키기 구현
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/domain/User.java
  src/main/java/com/nawabali/nawabali/repository/PostRepository.java
  src/main/java/com/nawabali/nawabali/service/KakaoService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#132 FEAT : 게시물 검색 시 반환값 추가 및 카테고리/id 로 필터링 기능 추가
  .idea/compiler.xml
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/PostSearch.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement, fix

#133 FIX : 게시물 검색 API 수정
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement, fix

#135 F EAT : ES 보안 추가
  build.gradle
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/UserSearch.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/UserSearchRepository.java
  src/main/java/com/nawabali/nawabali/security/Jwt/WebSocketJwtInterceptor.java
  src/main/resources/static/es-postmapping.json
  src/main/resources/static/es-setting.json
  src/main/resources/static/es-usersmapping.json
Labels: enhancement, fix

#136 FIX : 알림
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/domain/Notification.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#138 FIX : 알림 삭제 추가 & SSE heartbeattimeout
  .idea/compiler.xml
  src/main/java/com/nawabali/nawabali/controller/NotificationController.java
  src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: enhancement, fix

#139 FIX : 메세지 연결 오류
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
Labels: fix

#140 FIX : 알림 heartbeat 구현
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#141 Develop
  .gitignore
  .idea/dataSources.xml
  build.gradle
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/controller/KakaoController.java
  src/main/java/com/nawabali/nawabali/controller/NotificationController.java
  src/main/java/com/nawabali/nawabali/domain/Notification.java
  src/main/java/com/nawabali/nawabali/domain/elasticsearch/UserSearch.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/repository/ChatMessageRepository.java
  src/main/java/com/nawabali/nawabali/repository/NotificationRepository.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/UserSearchRepository.java
  src/main/java/com/nawabali/nawabali/security/Jwt/WebSocketJwtInterceptor.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/LikeService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
  src/main/resources/static/es-postmapping.json
  src/main/resources/static/es-setting.json
  src/main/resources/static/es-usersmapping.json
Labels: enhancement

#143 FIX : 알림 ioexception, 로그 추가
  .idea/compiler.xml
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#148 Feature/34/cicd notification
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: enhancement, fix

#149 FIX : 채팅방 입장 & 특정 채팅방 조회
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#142 FEAT : 썸네일 이미지 최적화
  .idea/dataSources.xml
  build.gradle
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/UserSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: enhancement

#150 본인 전체 채팅방 목록 반환
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
Labels: bug

#145 fix : CommentDslDto 삭제 후 CommentDto로 통합
  .idea/compiler.xml
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/dto/CommentDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
Labels: fix

#152 FIX : 게시물 상세보기 시 리사이즈 이미지 제외
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: fix

#153 FEAT : 지도 이미지 최적화 작업
  .gitattributes
  .github/workflows/cicd_production.yml
  .gitignore
  .idea/dataSources.xml
  appspec.yml
  build.gradle
  scripts/health.sh
  scripts/profile.sh
  scripts/start.sh
  scripts/stop.sh
  scripts/switch.sh
  src/main/java/com/nawabali/nawabali/config/ElasticSearchConfig.java
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/controller/CommentController.java
  src/main/java/com/nawabali/nawabali/controller/PostController.java
  src/main/java/com/nawabali/nawabali/domain/Chat.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/dto/CommentDto.java
  src/main/java/com/nawabali/nawabali/dto/PostDto.java
  src/main/java/com/nawabali/nawabali/dto/querydsl/CommentDslDto.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/PostSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/elasticsearch/UserSearchRepository.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/comment/CommentDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/post/PostDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/s3/AwsS3Service.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/CommentService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
Labels: fix

#156 FIX : 알림 관련 수정사항 (+unsubscribe)
  .idea/dataSources.xml
  src/main/java/com/nawabali/nawabali/controller/ChatRoomController.java
  src/main/java/com/nawabali/nawabali/dto/ChatDto.java
  src/main/java/com/nawabali/nawabali/global/websocket/WebSocketEventListener.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustom.java
  src/main/java/com/nawabali/nawabali/repository/querydsl/chat/ChatDslRepositoryCustomImpl.java
  src/main/java/com/nawabali/nawabali/service/ChatMessageService.java
  src/main/java/com/nawabali/nawabali/service/ChatRoomService.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: fix

#157 bug : 알람 비동기 처리
  src/main/java/com/nawabali/nawabali/controller/NotificationController.java
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: bug

#158 bug : 알림 클라이언트와 연결이 끊어졌을때 보안 & 알림 보내주는 형식 수정
  src/main/java/com/nawabali/nawabali/service/NotificationService.java
Labels: bug, fix

#160 Exception추가 및 api 수정
  .idea/compiler.xml
  .idea/dataSources.xml
  src/main/generated/com/nawabali/nawabali/domain/QUser.java
  src/main/java/com/nawabali/nawabali/NawabaliApplication.java
  src/main/java/com/nawabali/nawabali/config/WebSecurityConfig.java
  src/main/java/com/nawabali/nawabali/constant/CityEnum.java
  src/main/java/com/nawabali/nawabali/controller/KakaoController.java
  src/main/java/com/nawabali/nawabali/controller/UserController.java
  src/main/java/com/nawabali/nawabali/domain/User.java
  src/main/java/com/nawabali/nawabali/dto/UserDto.java
  src/main/java/com/nawabali/nawabali/exception/ErrorCode.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtAuthorizationFilter.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtExceptionHandlerFilter.java
  src/main/java/com/nawabali/nawabali/security/Jwt/JwtUtil.java
  src/main/java/com/nawabali/nawabali/service/KakaoService.java
  src/main/java/com/nawabali/nawabali/service/PostService.java
  src/main/java/com/nawabali/nawabali/service/UserService.java
Labels: enhancement, fix
